# Generated by fusen: do not edit by hand

test_that("extract_six_from_col works", {
  expect_length(extract_six_from_col(dataset = mtcars, column = "mpg"), 6)
  expect_type(extract_six_from_col(dataset = mtcars, column = "mpg"), "double")
  expect_error(extract_six_from_col(dataset = mtcars, column = "toto"))

})
